source 'http://rubygems.org'

gem 'rails', '3.0.7'

# http://stackoverflow.com/questions/5287121/undefined-method-task-using-rake-0-9-0-beta-4
gem 'rake' , '0.8.7'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'mysql2', '~> 0.2.7'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
gem 'capistrano'

gem 'devise'

gem 'cancan'

gem 'inline_forms'

gem 'paperclip'

gem 'will_paginate', :git => 'git://github.com/acesuares/will_paginate.git', :branch => 'rails3'

gem 'tabs_on_rails'

gem 'jrails'

gem 'jquery-rails'

gem 'remotipart', :git => 'git://github.com/JangoSteve/remotipart.git', :branch => 'latest-and-greatest'

gem "ckeditor", "~> 3.5.4"
#gem 'ckeditor', :git => 'git://github.com/galetahub/rails-ckeditor.git', :branch => 'rails3'
#gem 'ckeditor', :git => 'git://github.com/acesuares/rails-ckeditor.git', :branch => 'rails3'

#gem 'calendar_date_select' # not rails 3 compatible

# To use debugger (ruby-debug for Ruby 1.8.7+, ruby-debug19 for Ruby 1.9.2+)
# gem 'ruby-debug'
# gem 'ruby-debug19'

# Bundle the extra gems:
# gem 'bj'
# gem 'nokogiri'
# gem 'sqlite3-ruby', :require => 'sqlite3'
# gem 'aws-s3', :require => 'aws/s3'

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
# group :development, :test do
#   gem 'webrat'
# end
